googleinterns/scan-and-go

- client/src/components/StoreHeader.tsx
- client/src/components/StoreList.tsx
- client/src/pages/Home.tsx
- client/src/pages/ScanStore.tsx
- client/src/utils.tsx
refactor and remove callbacks from `fetchJson` and `fetchText`
> refactor fetch utils methods

- client/src/components/StoreHeader.tsx
- client/src/components/StoreList.tsx
- client/src/interfaces.tsx
- client/src/pages/ScanStore.tsx
* [Interface variable declaration syntax](https://www.tutorialsteacher.com/typescript/typescript-interface#:~:text=Interface%20as%20Type,a%20type%20of%20a%20variable.&text=It%20means%20only%20an%20object,assigned%20to%20a%20variable%20kv1%20.)
* camelCase naming convention
> Minor style changes

- EAN_chksum.py
- server/config.js
- server/controllers/api-controller.js
- server/controllers/items-controller.js
- server/controllers/stores-controller.js
- server/controllers/users-controller.js
- server/data/items.json
- server/firestore.js
- server/package.json
- server/routers/api-router.js
- server/server.js
- server/utils.js
- server/yarn.lock
- Updated `EAN_chksum.py` to use constants
- Added server files
> Added server files

- .gitignore
- EAN_chksum.py
- README.md
- server/config.js
- server/constants.js
- server/controllers/api-controller.js
- server/controllers/items-controller.js
- server/controllers/stores-controller.js
- server/controllers/users-controller.js
- server/data/items.json
- server/emulatedFirestore.js
- server/firestore.js
- server/package.json
- server/routers/api-router.js
- server/server.js
- server/tests/routes.test.js
- server/utils.js
- server/yarn.lock
- Added server testing framework
- Modified README.md to reflect necessary steps to run testing on server
> Server testing

- client/src/components/Components.tsx
- client/src/components/StoreHeader.tsx
- client/src/components/StoreList.tsx
- client/src/constants/index.tsx
- client/src/interfaces.tsx
- client/src/pages/Home.tsx
- client/src/pages/ScanStore.tsx
- client/src/utils.tsx
- Updated Constants to match server endpoints
> Server api update

- client/src/components/StoreList.tsx
- client/src/pages/ScanStore.tsx
Fixed:
- [BUG] Util function `fetchJson` arguments mismatch
- [BUG] Coordinate in `StoreList.tsx` not updating on location query
> Minor bug fixes to merge between PR #61 and #72

- EAN_chksum.py
- client/src/App.tsx
- client/src/components/Components.tsx
- client/src/components/StoreHeader.tsx
- client/src/components/StoreList.tsx
- client/src/constants/index.tsx
- client/src/css/Login.css
- client/src/interfaces.tsx
- client/src/pages/Home.tsx
- client/src/pages/Login.tsx
- client/src/pages/ScanStore.tsx
- client/src/utils.tsx
- server/config.js
- server/controllers/api-controller.js
- server/controllers/items-controller.js
- server/controllers/stores-controller.js
- server/controllers/users-controller.js
- server/data/items.json
- server/firestore.js
- server/package.json
- server/routers/api-router.js
- server/server.js
- server/utils.js
- server/yarn.lock
> Login page

- client/src/components/Components.tsx
- client/src/pages/Login.tsx
- client/src/tests/Login.test.tsx
- Added test for rendering of Login Page
- Added test for url redirect upon successful entry of user details
> Added testing script for default (web) rendering of Login Page | login url redirect on user login

- client/src/components/Components.tsx
- client/src/pages/Login.tsx
- client/src/tests/Login.test.tsx
- Added test for rendering of Login Page
- Added test for url redirect upon successful entry of user details
> Added testing script for rendering of Login Page | login url redirect on user login

- .github/workflows/lint.yml
Added prettier_extensions to selectively check files we are linting
- This removes .html files from our list of checked files
> Update lint.yml to only trigger on selected files

- server/constants.js
- server/controllers/orders-controller.js
- server/data/orders.json
- server/emulatedFirestore.js
- server/firestore.js
- server/routers/api-router.js
- server/tests/routes.test.js
* `api/order` adds an order to the orders collection
* `api/order/list` lists all orders for a given user
> Set up and test orders endpoint

- .github/workflows/test.yml
- client/package.json
- client/src/pages/Login/Login.test.tsx
- server/globalTestSetup.js
- Added `run-client-tests` in `.github/workflows/test.yml` to only trigger on pushes or pull_requests into `master` since `yarn` takes a while to install packages (limit usage)
> Added github action for client-side testing

- .github/workflows/lint.yml
- .github/workflows/test.yml
- client/package.json
- client/src/pages/Login/Login.test.tsx
- server/globalTestSetup.js
- server/package.json
- server/tests/routes.test.js
- server/yarn.lock
- Added `firebase-tools` to server dev dependencies
- Run `yarn test` with `firebase emulators:exec "yarn test"` command
Known issue #100 lengthens server test by ~1min
> Enabled server test to run when pushing to or making pull_request to master branch

- client/src/App.tsx
- client/src/components/StoreHeader/StoreHeader.test.tsx
- client/src/components/StoreHeader/StoreHeader.tsx
- client/src/components/StoreList/StoreList.tsx
- client/src/pages/Login/Login.test.tsx
- client/src/pages/Login/Login.tsx
- client/src/pages/Receipt/Receipt.tsx
- client/src/pages/ScanStore/ScanStore.tsx
- client/src/setupTests.ts
- Refactored calls to `window.location.*` for url redirects with `history.push` and `useHistory` hooks
- Introduced passing of variables to new component via `location.state`
- Modified tests to mock `useHistory().push` function to test for calls to url redirects
> Refactored client to use react-router-dom via useHistory hook

- client/src/components/StoreCard/StoreCard.test.tsx
- client/src/components/StoreCard/StoreCard.tsx
- client/src/components/StoreList/StoreList.test.tsx
- client/src/components/StoreList/StoreList.tsx
- client/src/components/UserHeader/UserHeader.test.tsx
- client/src/pages/Login/Login.test.tsx
- client/src/theme.ts
- client/src/transforms.ts
- Added tests for:
- `StoreCard`
- `StoreList`
- `UserHeader`
> Tests for StoreCard/StoreList/UserHeader UI components

- README.md
- Add instructions to install node and npm and yarn
- Add instructions to install packages
> Update README with instructions to install pre-requisites and dependencies before running

- .github/workflows/test.yml
Test PR whether test actions will run when we issue PR to another branch that is not `master`
> Amended test.yml to run test action for all PR

- client/src/components/CartHeader/CartHeader.test.tsx
- client/src/components/Header/Header.test.tsx
- client/src/components/Header/Header.tsx
- client/src/components/UserHeader/UserHeader.test.tsx
- client/src/utils.ts
- Added rendering test for specified Elements into Header prop fields
> Added tests for rendering and interacting with Header components

- .gitignore
- client/src/components/Cart/Cart.tsx
- client/src/components/CartHeader/CartHeader.test.tsx
- client/src/components/CartHeader/CartHeader.tsx
- client/src/components/Header/Header.test.tsx
- client/src/components/Header/Header.tsx
- client/src/components/ItemCard/ItemCard.tsx
- client/src/components/ItemCard/ItemCardMedia.tsx
- client/src/components/ItemCard/ItemCardQuantityMixer.tsx
- client/src/components/StoreCard/StoreCard.tsx
- client/src/components/UserHeader/UserHeader.test.tsx
- client/src/components/UserHeader/UserHeader.tsx
- client/src/constants.ts
- client/src/interfaces.ts
- client/src/pages/ScanStore/ScanStore.tsx
- client/src/theme.ts
- client/src/utils.ts
- Updated ItemCard to match mockup card layout
- Added optional `media: string;` field to `Item` in `interfaces.ts`, updated some Firestore DB items with this additional field
- Added optional `detail: string;` field to `Item` in `interfaces.ts`
- Abstracted some text parsing functions into `utils.ts`
> Updated ItemCard component to show layout of item details

- README.md
- client/jsdoc.conf.json
- client/package.json
- client/yarn.lock
- package.json
Run `yarn doc` to create the jsdocs
> Configure git-secrets pre-commit hook and jsdoc script

- client/src/components/ItemCard/ItemCard.tsx
- client/src/components/ItemCard/ItemCardMedia.tsx
- client/src/components/ItemCard/ItemCardQuantityMixer.tsx
- client/src/pages/Actions.ts
- client/src/pages/Home/DebugBar.tsx
- client/src/pages/Login/Login.tsx
- Used 'vw' to set ItemCardMedia image height&width to 15% of screen width
- Further constrained by absolute maxHeight limit as specified with constant
- Fixed login Action function not returning `IdentityToken` but a promise instead, `user.name` now correctly shows up in microapp Main page with greeting message
> Adjusted height constrain of ItemCardMedia to better fit mobile interface | Fixed login bug user.name not showing

- client/src/components/StoreCard/StoreCard.test.tsx
- client/src/components/StoreCard/StoreCard.tsx
- client/src/components/StoreList/StoreList.tsx
- client/src/pages/Actions.ts
- client/src/pages/Home/DebugBar.tsx
- client/src/pages/Home/Home.tsx
- server/tests/routes.test.js
- Abstracted formation of store url into Action.ts
- Minor for loop replacement with map
> Minor refactoring of URL generation code and usage of for loops

- client/src/components/CartSummary/CartSummary.test.tsx
- client/src/components/CartSummary/CartSummary.tsx
- client/src/components/IconSearchBar/IconSearchBar.test.tsx
- client/src/components/IconSearchBar/IconSearchBar.tsx
- client/src/components/MediaInfoCard/MediaInfoCard.test.tsx
- client/src/components/PlaceholderCart/PlaceholderCart.test.tsx
- client/src/components/PlaceholderStoreList/PlaceholderStoreList.test.tsx
Added tests for:
- IconSearchBar
- MediaInfoCard
- #183 Testing blur callback directly, missing test for keypress "Enter" triggering blur
- CartSummary
- PlaceholderStoreList
- PlaceholderCart
> Improved test coverage for newly added UI components

- client/src/components/Cart/Cart.tsx
- client/src/components/CartSummary/CartSummary.tsx
- client/src/components/Header/Header.tsx
- client/src/components/ReceiptHeader/ReceiptHeader.tsx
- client/src/components/ReceiptHeader/index.tsx
- client/src/pages/Page.tsx
- client/src/pages/Receipt/Receipt.tsx
- client/src/pages/ScanStore/ScanStore.tsx
- Abstracted Grid layout from `ScanStore.tsx` into `Page.tsx` and reused in `Receipt.tsx` for consistency in UI layout
- Moved `ReceiptHeader` subcomponent into `src/component/ReceiptHeader` and moved rendering logic into `Cart` for consistency between 'compact view' and 'receipt view'
> Made Receipt page layout more consistent with rest of the pages

- client/package.json
- client/yarn.lock
- server/package.json
- server/yarn.lock
Address security alert from dependabot on lodash vulnerability
> Patch lodash to ^4.17.19

- client/src/components/ItemCard/ItemCardQuantityMixer.tsx
- client/src/components/ItemDetail/ItemDetail.tsx
- client/src/pages/ScanStore/ScanStore.tsx
- Refactored flow for adding new item:
- Scan -> ItemDetail -> AddToCart
- Added deletion confirmation dialog
**Demo:**
**Cancelling dialogs:**
**Note: Known issue with subtotal not updating in shown demos, this is fixed in this PR**
> Added Confirmation Dialog for removing item and adding new item

- client/src/components/AuthenticatedRoute/AuthenticatedRoute.tsx
- client/src/components/ItemDetail/ItemDetail.test.tsx
- client/src/components/ItemDetail/ItemDetail.tsx
- client/src/components/UserHeader/UserHeader.test.tsx
- client/src/components/UserHeader/UserHeader.tsx
- client/src/constants.ts
- client/src/contexts/AuthContext.tsx
- client/src/interfaces.ts
- client/src/pages/Actions.ts
- client/src/pages/Login/Login.test.tsx
- client/src/pages/Login/Login.tsx
- client/src/pages/Orders/Orders.tsx
- Standardize `empty...` syntax as constructor
- `emptyUser` was const object instead
- updated `user === emptyUser` checks for no user login with `!user["user-id"]`
- Moved time-of-day greeting message into 'subtitle' in UserHeader
- Replaced Greeting with 'Hey' or 'Welcome' (for not-yet-logged-in user) in title
- Updated tests to work with the new changes
- Removed obsolete clock function in UserHeader
> standardized emptyUser as constructor | Added default welcome message to UserHeader

- client/src/components/ItemCard/ItemCardQuantityMixer.tsx
- client/src/pages/Actions.ts
- client/src/pages/ScanStore/ScanStore.test.tsx
- client/src/pages/ScanStore/ScanStore.tsx
* Cache cart
* Empty cart message placeholder
* Item quantity buttons
* Fix collapse/expand buttons
* Disable checkout buttons when cart empty or already checking out
> Scanstore UI

- client/src/App.tsx
- client/src/components/AuthenticatedRoute/AuthenticatedRoute.tsx
- client/src/constants.ts
- client/src/pages/Actions.ts
- client/src/pages/Login/Login.tsx
Ensure that we call getIdentity on every app launch, in case the user revoked permissions in between sessions
> call getIdentity when initializing user state | minor edits

- client/src/helpers/storeSearch.test.ts
- client/src/helpers/storeSearch.ts
- client/src/packages/Heap.test.ts
Tests for #241 
* `Heap.test.tsx`: Tests for Heap class
* `storeSearch.test.tsx`: Tests for exported store search functions `preprocess` and `getTopKStoreIds`
* [WIP] `Home.test.tsx`: Tests for store search UI events
> Store search tests
